---
title: "EcoPlate - Pilot Experiments"
author: "Jay T. Lennon"
date: "`r format(Sys.time(), '%d %B, %Y')`"
header-includes:
   - \usepackage{array}
output: pdf_document
geometry: margin=2.54cm
---

## OVERVIEW
A pilot experiment using KBS0723 (Psuedomonas) that have been unstarved or 
starved for three years.
We screened the two strains on EcoPlate (Biolog) to see if their resource use 
profiles changed in response to starvation

## 1) SET WORKING DIRECTORY AND LOAD DATA
```{r}
rm(list=ls()) 
getwd()
setwd("/Users/lennonj/GitHub/StarvationTraits")
KBS0723 <- read.table("data/EcoPlate/data/0723_pilot.txt", sep="\t", header=TRUE)
KBS0723_3C <- read.table("data/EcoPlate/data/0723_3C_pilot.txt", sep="\t", header=TRUE)
```

## 2) TEST FOR CORRELATION BETWEEN TWO PROFILES
```{r}
require(vegan)
KBS0723.dist <- vegdist(KBS0723, method = "jaccard")
KBS0723_3C.dist <- vegdist(KBS0723_3C, method = "jaccard") 
mant.pear <- mantel(KBS0723.dist, KBS0723_3C.dist, method = "pearson", permutations = 999)
mant.spear <- mantel(KBS0723.dist, KBS0723_3C.dist, method = "spear", permutations = 999)
```

